---
title: "Hypergeometric test for the overlap of two gene sets"
output: html_document
---

```{r}
# alorenzetti 20230410

# description ####
# this script will evaluate
# the probability of obtaining
# a value as extreme of more extreme
# than the overlap of two sets of genes

# loading libs ####
library(tidyverse)
library(ggpubr)

# getting started ####
# the first set is the number
# of genes bound to RhlB in vivo
# without rRNAs: CCNA_R0066, CCNA_R0069, CCNA_R0087, CCNA_R0084
setA = 216

# the second set is the number
# of differentially expressed genes at 10C
# without rRNAs: CCNA_R0066, CCNA_R0069, CCNA_R0087, CCNA_R0084
setB = 478

# the genes showing up in the two sets
# is the overlap
overlap = 74

# the total number of genes in C. crescentus 
# according to the NA1000 genome build at the NCBI
# without rRNAs: CCNA_R0066, CCNA_R0069, CCNA_R0087, CCNA_R0084
total = 4081
```

```{r}
# those numbers are sufficient to define the
# parameters of the hypergeometric distribution
# to generate a null distribution and then compare
# the observed overlap to see if the overlap
# is more extreme than the null distribution for
# the same parameters.
# plotting the histogram for the null distribution
# with 10000 observations
set.seed(665)
null = rhyper(nn = 10000, m = setA, n = total-setA, k = setB)
head(null, 200)
```

```{r}
# the overlap is almost 3x bigger than
# the median of the null distribution (obtained at random)
# print("Median of the null distribution:")
median(null)

# print("Mean of the null distribution:")
mean(null)

# print("Representation factor:")
overlap/median(null)
```

```{r}
# the probability (p-value) of obtaining a value
# as extreme or more extreme than the overlap (74)
# given a null distribution (obtained at random)
# with the same parameters is
p = phyper(q = overlap-1, m = setA, n = total-setA, k = setB, lower.tail = F)

# print("Probability of of obtaining a value as extreme or more extreme than the overlap given a null distribution (obtained at random) with the same parameters:")
p
```

```{r}
# the observed overlap was 74
# whereas the median of our null distribution obtained
# at random was around 26
plot = tibble(null = null) %>% 
  ggplot(aes(x = null)) +
  geom_histogram(fill = "white", color = "black", bins = 30) + # Adjust the number of bins to a suitable value, e.g., 30
  geom_vline(aes(xintercept = median(null), color = "Median of null distribution"),
             linetype="dashed", show.legend = TRUE) +
  geom_vline(aes(xintercept = overlap, color = "Observed gene set overlap"),
             linetype="dashed", show.legend = TRUE) +
  theme_pubr() +
  xlab("Number of observations") +
  ylab("Frequency") +
  labs(caption = paste0("Probability of the observed overlap or a greater value given the null distribution: ", format(p, digits = 3, scientific = T))) +
  scale_color_manual(values = c("#4E79A7", "#E15759")) +
  scale_x_continuous(breaks = seq(0, 80, by = 5)) +
  theme(legend.position = "bottom", legend.title = element_blank())

plot
```

```{r}
# saving plot
ggsave(filename = "plots/overlap_significance.png",
       plot = plot,
       unit = "in",
       height = 4, width = 6,
       dpi = 600)
```

